-- Local Hams seed data — FCC ULS export for Church Hill, Kingsport, Mount Carmel TN
-- Clubs (W4ZJA, W4TRC) excluded; only individual licensees

INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('W0HVC','JAMES','BERRY','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4KTB','GERALD','CARDWELL','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4ADP','Robert','Click','Church Hill','TN','37642-6623');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4KRG','Kyle','Gonzales','Church Hill','TN','37642-6308');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4ACF','Robert','Harless','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4GFC','Rebecca','Larkins','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4GFD','Terry','Larkins','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4LEW','JAMES','MERRILL','Church Hill','TN','37642-5090');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4BGY','LINDA','MOENTER','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4FTN','FRED','MOORE','Church Hill','TN','37642-3225');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4ADS','VIRGIL','ROSE','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WD4GTK','JAMES','SEXTON','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4DOC','CHRISTOPHER','SMITH','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4DOB','MARK','SNAPP','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4ZRI','CHARLES','STILL','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4SEP','William','Warden','Church Hill','TN','37642-4554');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4GNF','Robert','Abbott','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4CYS','Aaron','Ables','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4DDL','Braeden','Ables','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4VPR','Daniel','Bogard','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4LOW','Jason','Breeding','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4LEK','Guy','Chacon','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4PHD','Roger','Ellis','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4MYI','Christopher','Estep','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4JHO','Michael','Fansler','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4BIN','Mary','Fisher','Church Hill','TN','37642-3606');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4KYN','DAVID','GOTT','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4KCX','Melissa','Hamilton','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4ZRC','Andy','Harless','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4TPC','James','Herron','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4RQN','WILLIAM','LAWSON','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4CEV','Robert','Lacy','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4KPR','Daniel','McMurray','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4ZAS','Norwood','Moore','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4LZC','Rebecca','Parton','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4PXN','Donald','Phillips','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4KDD','Ronald','Redwine','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4KDB','Adrian','Smith','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4UUS','Joseph','Smith','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4WVN','James','Sutton','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC8KMV','JOSEPH','WHITSON','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4WIJ','Sophia','Webb','Church Hill','TN','37642');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA4R','DONALD','BAKER','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KT4AV','MARK','BELLAMY','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4MMF','NORMAN','BLACKMAN','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4EMK','RICHARD','BOWERY','Kingsport','TN','37664-3933');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K8UHC','LARRY','BRAMMER','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB1CWD','LOIS','BRONSON','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N1UAN','ROBERT','BRUNDIGE','Kingsport','TN','37660-3942');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WA4RXK','ROBERT','BURNS','Kingsport','TN','37660-7868');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4CBP','CHARLES','BUSTETTER','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4GFL','James','Brice','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4URE','CHRISTOPHER','CARTER','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WD4OUM','TERRY','CASEY','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WD4PKD','ANDREA','CHEAK','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WD4OQY','WILLIAM','CHEAK','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4PCJ','BOBBY','COLE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4PXE','TIMOTHY','COMPTON','Kingsport','TN','37660-1293');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC4TCN','DONALD','CRAWFORD','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4MWN','LYLE','CROSBY','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB4JTF','ALLEN','CROSS','Kingsport','TN','37664-5351');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WA4LBN','ALLEN','CROSS','Kingsport','TN','37664-5351');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB4FNT','PHYLLIS','CROSS','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA4ICK','MARK','DEBORD','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4DOD','TERRY','DIAMOND','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4CBQ','MERTON','DIBBLE','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WA4AOQ','MICHAEL','DUNN','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4ICI','Cullen','Duke','Kingsport','TN','37663-2242');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4YYB','ELIJAH','ELLIS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4YYJ','JOHN','ELLIS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4PJK','David','Easterling','Kingsport','TN','37663-2886');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4MKN','JONATHAN','FIELDS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA4PJB','VERLIN','FORD','Kingsport','TN','37663-3520');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4HIT','LARRY','FRAYSIER','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4YGM','JEFFREY','FRENCH','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4BPV','CATHY','GARRETT','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4IYO','ETHAN','GIBSON','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4LSD','ANTHONY','GILLIAM','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4ZTN','CATHY','GOTT','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4GOO','Lionel','Grady','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC4WTZ','MARK','HAMBLEN','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC4YQL','RICHARD','HEPPERT','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4ISW','SUSAN','HILL','Kingsport','TN','37663-2883');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WD4BHB','JOHNNY','HOOD','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4HGK','FRED','HORNE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB4JM','WILLIAM','HORTON','Kingsport','TN','37664-2039');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC4LKF','GARY','HUGHES','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB8ZRX','JEFFREY','HUTCHISON','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4HZI','Shannon','Hite','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4OOA','LEROY','JESSEE','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K4FOP','BOBBY','JONES','Kingsport','TN','37663-3200');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WD4EIT','DANNIE','JONES','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4EZD','JAMES','KETRON','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4YMJ','HERMIN','LANE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4TMW','ROBERT','LANGAN','Kingsport','TN','37663-3288');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4BUD','BILL','LINEBACK','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4QXN','WILLIAM','LITZ','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WB2PEE','STEVEN','LOIACONO','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WM5K','GARRETT','LUCE','Kingsport','TN','37660-2956');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4WJP','Daniel','Lane','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4DMP','Michael','Lathrop','Kingsport','TN','37663-2886');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4WZG','Ronald','Light','Kingsport','TN','37664-4362');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA4LSR','LARRY','MALONE','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AA4AA','KENNETH','MANESS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4OSB','JUSTIN','MANN','Kingsport','TN','37663-2970');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC4TCO','GEORGE','MARCUM','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AC4QZ','PAUL','MARCUM','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AD4RS','DONALD','MARSHALL','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AB4TY','KENNEY','MC NABB','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4WCN','CHARLES','MIMS','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WB4RUX','JAMES','MOORE','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4MTQ','STEPHEN','MOWRY','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AE4IA','DONALD','MULLINS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4DTW','Henry','Maness','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4DTX','Phyllis','Maness','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4ECN','Michael','McConnell','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4MUM','STANLEY','OKRASINSKI','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4LX','HOBERT','OLINGER','Kingsport','TN','37660-6220');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4YYO','ERIC','OLSEN','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4YYP','LIDA','OLSEN','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WA4FIT','PHYLLIS','OSBORNE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K4LN','WILLIAM','OSBORNE','Kingsport','TN','37663-2200');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4AWG','WALTER','OWENBY','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K4VVN','JAMES','PADGETT','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4DNV','KATHERINE','PADGETT','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WA4BGS','STANLEY','PEIRCE','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4DRG','KENNETH','PERRY','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4LOZ','Randall','Prillaman','Kingsport','TN','37660-4711');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4HOW','ISSAC','QUILLEN','Kingsport','TN','37660-1307');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4NDP','NANCY','QUILLEN','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('W4LYS','PERRY','RAMSEY','Kingsport','TN','37664-5267');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K4EUO','DANIEL','REECE','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4GUL','EDGAR','ROACHE','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4OXI','CHRISTOPHER','ROBBINS','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4TMY','JOHN','SACKETT','Kingsport','TN','37660-1436');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4ISN','AARON','SAMS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KT4NG','TOMMY','SANDERS','Kingsport','TN','37660-6836');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE5DSO','GARY','SAVAGE','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4AFC','KENNETH','SCHERER','Kingsport','TN','37665');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4OPX','GEORGE','SHELTON','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4VAX','KIMBERLY','SHELTON','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4RIW','PAIGE','SHIPLEY','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('NA4E','DAVID','SMITH','Kingsport','TN','37665');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K4VZZ','GARY','SMITH','Kingsport','TN','37660-1829');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4BGW','STEPHEN','STEWART','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4TNS','BILLY','TAYLOR','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4TNT','JENNIFER','TAYLOR','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4CJZ','DANIEL','THOUIN','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KD4KOY','JERRY','TOMLINSON','Kingsport','TN','37665');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4MVX','JIMMY','TROTTER','Kingsport','TN','37660-5021');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AA4DL','ROLLA','WADE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4AEL','JAMES','WALSH','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4OFA','MIKE','WECHSLER','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4RPN','DONALD','WHITE','Kingsport','TN','37660-3414');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4JNL','Steve','Wells','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4JID','Cora','Whaley','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4TG','RALPH','YOUNG','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4QZD','Jeffrey','Allen','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA4ZYE','William','Allen','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KX4NU','Peter','Alley','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4FFO','Philip','Alley','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4LVK','Alex','Anderson','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4ENK','Michael','Anderson','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4JNL','Darren','Arnold','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4YBX','Jeffery','Ausband','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4BIJ','MICHAEL','BACON','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WB4NDA','EARL','BAILEY','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4YTT','DAVID','BARNETTE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KD7JHD','DALLIN','BASTIAN','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4CCP','Matthew','Babler','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4WFK','Nathaniel','Bailey','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4DPZ','Daniel','Barbrow','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KZ4ED','John','Barnthouse','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4KLL','Jessica','Beare Edmunds','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4AEK','James','Beasley','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4GTH','Jonathan','Beck','Kingsport','TN','37663-2407');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KX4OE','Justin','Beeler','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4CYC','Phillip','Bentley','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4OSL','Lester','Bingaman','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4CMP','Jason','Blankenship','Kingsport','TN','37665');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4MOC','Faith','Bogard','Kingsport','TN','37660-7944');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4GCS','John','Boyd','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA3BAB','Kevin','Broughton','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4LZD','James','Burleson','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA1KAU','MARIA','CAMPBELL','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4MOM','JAMES','CAUDILL','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4CYU','JAMES','COLE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WH6MA','STERLING','CORNWELL','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WB8POH','DAVID','CROSS','Kingsport','TN','37660-7469');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WH6EMF','GOLDIE','CROSS','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4TIQ','Joshua','Campbell','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4JHN','Myra','Carter','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4QGZ','Cristian','Chavez','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4GLA','Jesus','Chavez','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4MYW','Santo','Cicirello','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4PMK','Lisa','Cole','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4CDM','Christina','Compton','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4DCD','Rodney','Compton','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4DXL','Howard','Cone','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4RBV','Bill','Creasy','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4LYZ','Morgan','Davis','Kingsport','TN','37664-4711');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4FXG','Dale','DeBoer','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI5SF','Carl','DeWhitt','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4NMX','Samuel','Deaton','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4VPS','Jesse','Delatte','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4ESZ','Michael','Dent','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4OPL','Deemer','Diep','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4OGZ','Ellen','Diep','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4EZG','Stephen','Dockery','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4MYO','Laura','Donahue Ortiz','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KD4DZA','ANTHONY','EWING','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4HVL','Daniel','Ellis','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4TCG','William','Ewing','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4IKK','Edward','Fantin','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4PCX','Justin','Farris','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4WBA','Ralph','Fig','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4DCL','Daniel','Fisher','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4HZJ','Keshia','Fletcher','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WY2L','Kris','Francis','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB4BYH','Roger','Gillis','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4MKM','Anita','Gulley','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4AAU','David','Gulley','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4UFD','David','Hall','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4HEB','David','Hancock','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4IYE','Elizabeth','Harbin-Dabbs','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4TCE','Norman','Haynes','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4ALP','David','Helton','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4EJO','Aaron','Henderson','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4CMM','John','Herndon','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4NJZ','Michael','Hickman','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4YZJ','Mack','Hicks','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4WPG','John','Hill','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4OMY','Michael','Hobbs','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4WMZ','Lori','Holbrook','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4WNC','Roger','Holbrook','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4DOS','William','Honeycutt','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4IEL','Benjamin','Hunt','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KD7AJR','WENDY','JACKSON','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC2KAF','Ibrahim','Jardines','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4UWQ','Joseph','Jaynes','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4HLK','Calvin','Jenkins','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4PRN','Rodger','Jones','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4NCP','Tim','Jones','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4VOL','Jason','Jordan','Kingsport','TN','37664-4627');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4JBO','JOHN','KLIESCH','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WB4KYA','Robert','Kirk','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4NCK','Eli','Kistner','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4TRF','Matthew','Kitzmiller','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4HFW','CHRISTOPHER','LEWIS','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KY4RN','FRANK','LIEBE','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4XTJ','JEFFREY','LIGHT','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4CPR','CHRISTOPHER','LINEBACK','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4TOF','Michael','Lambert','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO6JQH','Chandler','Lane','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4SQS','Gregory','Laughlin','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC3FIH','Bruce','Lawrence','Kingsport','TN','37665');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4ZFJ','Timothy','Lee','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4CPW','Monte','Leonhart','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4VIW','Martin','Lewis','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4LSY','Johanna','Liebe','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4HDP','Ernest','Lipps','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4DWW','Jerry','Littlejohn','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4GIU','Debra','Long','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4WEF','Michael','Long','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4VPM','David','Loo','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4FWY','Donald','Masingale','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N3VBR','Dennis','Mattaliano','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4NUK','Gary','Mayes','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4HFV','Robert','Mayo','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4ECL','Debra','McConnell','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4GOC','Becky','McCord','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4JVN','Everett','McDuffie','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4ZAR','Michael','McQueen','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4NBM','C','Miles','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4DCM','Thomas','Moody','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4WEB','Grady','Moore','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4FUV','Christopher','Moreland','Kingsport','TN','37664-2007');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4TND','Kevin','Morrell','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4VCT','Andrew','Mullen','Kingsport','TN','37665');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AK4PO','William','Murdoch','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4PST','David','Murray','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4WJL','Sylvia','Nickels','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4ZPW','Jessica','Nomack','Kingsport','TN','37663-3630');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4JHF','James','Nottingham','Kingsport','TN','37660-7041');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4NAW','Robin','Oaks','Kingsport','TN','37663-3040');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4MYP','Mark','Ortiz','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4ISI','Michael','Overbay','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4LJ','Robert','Oyler','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N5LMS','CHARLES','POWELL','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KO4VPL','Morgan','Penn','Kingsport','TN','37617');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AB4H','Forrest','Pilgrim','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4KPH','Kenneth','Porter','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4CVU','Tom','Price','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4CLQ','KEVIN','REPASS','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4KDC','Patrick','Redwine','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('AD4UM','Joe','Riggs','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4CAO','Rebecca','Riggs','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB3KKX','Jeffrey','Robinson','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4GND','Nathan','Rogers','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4IR','Jimmy','Roller','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4SIQ','HARRISON','SCHMITT','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KC5QQK','DEAN','SPARKS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA4IWG','Martin','Schick','Kingsport','TN','37663-2930');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4ABM','Heather','Schneider','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4ABN','Kyle','Schneider','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB4EJ','Larry','Sentelle','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4NMV','Mark','Smith','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4MTT','Timothy','Smith','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4FPB','Eric','Stanton','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KA6ZRJ','Gustave','Stensler','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ6SQN','Kalani','Storey','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4TUX','BOYD','TRAVIS','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4KYM','John','Taylor','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4MGN','Malcolm','Tipton','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4VXR','Ransom','Tipton','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KF4FMK','CHRISTOPHER','VAUGHN','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4MXJ','Larry','Vanzant','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4CWF','Michael','Vaughn','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4WMN','William','Vaughn','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('K4GQX','Jack','Vest','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4MSP','Kellye','Voigt','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N5OWU','ANTHONY','WEST','Kingsport','TN','37664-0474');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KG4HZK','William','Watkins','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4NWH','Neil','Weber','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4UPH','Robert','Wells','Kingsport','TN','37660');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KV4LZ','Gary','Whalen','Kingsport','TN','37664-3654');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KJ4MJJ','Wayne','Wheeler','Kingsport','TN','37663');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KN4HLM','John','White','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KD7VMR','David','Williams','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('N4DW','David','Wilson','Kingsport','TN','37664');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4BYG','BONNIE','ANDERSON','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KE4IFP','Lee','Britt','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KY4WG','HENRY','CRAWFORD','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4YTD','Toni','Coplen','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KB4JTC','WILLIAM','GRANDY','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4DQU','TRAVIS','HUTCHISON','Mount Carmel','TN','37645-1930');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('WB4KSO','ROBERT','SENTER','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4JNQ','Randy','Elkins','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KR4KOA','Danny','Greene','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KQ4PGA','Ronald','Gross','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4YIM','Richard','Ragle','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KM4PJX','Adam','Thomas','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4ZCS','April','Wells','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KK4WZO','Michael','Wells','Mount Carmel','TN','37645');
INSERT OR IGNORE INTO prospects (callsign, first_name, last_name, city, state, zip) VALUES ('KI4TRZ','Monalisa','Deaton','Kingsport','TN','37664');
